-- Migrate display IDs from Greek letter format to 3-letter block format
-- Greek letters map to sequential blocks: alpha→AAA, beta→AAB, ..., omega→AAX

UPDATE humans SET display_id = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(display_id, '-omega-', '-AAX-'), '-psi-', '-AAW-'), '-chi-', '-AAV-'), '-phi-', '-AAU-'), '-upsilon-', '-AAT-'), '-tau-', '-AAS-'), '-sigma-', '-AAR-'), '-rho-', '-AAQ-'), '-pi-', '-AAP-'), '-omicron-', '-AAO-'), '-xi-', '-AAN-'), '-nu-', '-AAM-'), '-mu-', '-AAL-'), '-lambda-', '-AAK-'), '-kappa-', '-AAJ-'), '-iota-', '-AAI-'), '-theta-', '-AAH-'), '-eta-', '-AAG-'), '-zeta-', '-AAF-'), '-epsilon-', '-AAE-'), '-delta-', '-AAD-'), '-gamma-', '-AAC-'), '-beta-', '-AAB-'), '-alpha-', '-AAA-') WHERE display_id IS NOT NULL;

UPDATE accounts SET display_id = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(display_id, '-omega-', '-AAX-'), '-psi-', '-AAW-'), '-chi-', '-AAV-'), '-phi-', '-AAU-'), '-upsilon-', '-AAT-'), '-tau-', '-AAS-'), '-sigma-', '-AAR-'), '-rho-', '-AAQ-'), '-pi-', '-AAP-'), '-omicron-', '-AAO-'), '-xi-', '-AAN-'), '-nu-', '-AAM-'), '-mu-', '-AAL-'), '-lambda-', '-AAK-'), '-kappa-', '-AAJ-'), '-iota-', '-AAI-'), '-theta-', '-AAH-'), '-eta-', '-AAG-'), '-zeta-', '-AAF-'), '-epsilon-', '-AAE-'), '-delta-', '-AAD-'), '-gamma-', '-AAC-'), '-beta-', '-AAB-'), '-alpha-', '-AAA-') WHERE display_id IS NOT NULL;

UPDATE activities SET display_id = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(display_id, '-omega-', '-AAX-'), '-psi-', '-AAW-'), '-chi-', '-AAV-'), '-phi-', '-AAU-'), '-upsilon-', '-AAT-'), '-tau-', '-AAS-'), '-sigma-', '-AAR-'), '-rho-', '-AAQ-'), '-pi-', '-AAP-'), '-omicron-', '-AAO-'), '-xi-', '-AAN-'), '-nu-', '-AAM-'), '-mu-', '-AAL-'), '-lambda-', '-AAK-'), '-kappa-', '-AAJ-'), '-iota-', '-AAI-'), '-theta-', '-AAH-'), '-eta-', '-AAG-'), '-zeta-', '-AAF-'), '-epsilon-', '-AAE-'), '-delta-', '-AAD-'), '-gamma-', '-AAC-'), '-beta-', '-AAB-'), '-alpha-', '-AAA-') WHERE display_id IS NOT NULL;

UPDATE colleagues SET display_id = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(display_id, '-omega-', '-AAX-'), '-psi-', '-AAW-'), '-chi-', '-AAV-'), '-phi-', '-AAU-'), '-upsilon-', '-AAT-'), '-tau-', '-AAS-'), '-sigma-', '-AAR-'), '-rho-', '-AAQ-'), '-pi-', '-AAP-'), '-omicron-', '-AAO-'), '-xi-', '-AAN-'), '-nu-', '-AAM-'), '-mu-', '-AAL-'), '-lambda-', '-AAK-'), '-kappa-', '-AAJ-'), '-iota-', '-AAI-'), '-theta-', '-AAH-'), '-eta-', '-AAG-'), '-zeta-', '-AAF-'), '-epsilon-', '-AAE-'), '-delta-', '-AAD-'), '-gamma-', '-AAC-'), '-beta-', '-AAB-'), '-alpha-', '-AAA-') WHERE display_id IS NOT NULL;

UPDATE lead_sources SET display_id = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(display_id, '-omega-', '-AAX-'), '-psi-', '-AAW-'), '-chi-', '-AAV-'), '-phi-', '-AAU-'), '-upsilon-', '-AAT-'), '-tau-', '-AAS-'), '-sigma-', '-AAR-'), '-rho-', '-AAQ-'), '-pi-', '-AAP-'), '-omicron-', '-AAO-'), '-xi-', '-AAN-'), '-nu-', '-AAM-'), '-mu-', '-AAL-'), '-lambda-', '-AAK-'), '-kappa-', '-AAJ-'), '-iota-', '-AAI-'), '-theta-', '-AAH-'), '-eta-', '-AAG-'), '-zeta-', '-AAF-'), '-epsilon-', '-AAE-'), '-delta-', '-AAD-'), '-gamma-', '-AAC-'), '-beta-', '-AAB-'), '-alpha-', '-AAA-') WHERE display_id IS NOT NULL;

UPDATE lead_events SET display_id = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(display_id, '-omega-', '-AAX-'), '-psi-', '-AAW-'), '-chi-', '-AAV-'), '-phi-', '-AAU-'), '-upsilon-', '-AAT-'), '-tau-', '-AAS-'), '-sigma-', '-AAR-'), '-rho-', '-AAQ-'), '-pi-', '-AAP-'), '-omicron-', '-AAO-'), '-xi-', '-AAN-'), '-nu-', '-AAM-'), '-mu-', '-AAL-'), '-lambda-', '-AAK-'), '-kappa-', '-AAJ-'), '-iota-', '-AAI-'), '-theta-', '-AAH-'), '-eta-', '-AAG-'), '-zeta-', '-AAF-'), '-epsilon-', '-AAE-'), '-delta-', '-AAD-'), '-gamma-', '-AAC-'), '-beta-', '-AAB-'), '-alpha-', '-AAA-') WHERE display_id IS NOT NULL;

UPDATE geo_interests SET display_id = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(display_id, '-omega-', '-AAX-'), '-psi-', '-AAW-'), '-chi-', '-AAV-'), '-phi-', '-AAU-'), '-upsilon-', '-AAT-'), '-tau-', '-AAS-'), '-sigma-', '-AAR-'), '-rho-', '-AAQ-'), '-pi-', '-AAP-'), '-omicron-', '-AAO-'), '-xi-', '-AAN-'), '-nu-', '-AAM-'), '-mu-', '-AAL-'), '-lambda-', '-AAK-'), '-kappa-', '-AAJ-'), '-iota-', '-AAI-'), '-theta-', '-AAH-'), '-eta-', '-AAG-'), '-zeta-', '-AAF-'), '-epsilon-', '-AAE-'), '-delta-', '-AAD-'), '-gamma-', '-AAC-'), '-beta-', '-AAB-'), '-alpha-', '-AAA-') WHERE display_id IS NOT NULL;

UPDATE geo_interest_expressions SET display_id = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(display_id, '-omega-', '-AAX-'), '-psi-', '-AAW-'), '-chi-', '-AAV-'), '-phi-', '-AAU-'), '-upsilon-', '-AAT-'), '-tau-', '-AAS-'), '-sigma-', '-AAR-'), '-rho-', '-AAQ-'), '-pi-', '-AAP-'), '-omicron-', '-AAO-'), '-xi-', '-AAN-'), '-nu-', '-AAM-'), '-mu-', '-AAL-'), '-lambda-', '-AAK-'), '-kappa-', '-AAJ-'), '-iota-', '-AAI-'), '-theta-', '-AAH-'), '-eta-', '-AAG-'), '-zeta-', '-AAF-'), '-epsilon-', '-AAE-'), '-delta-', '-AAD-'), '-gamma-', '-AAC-'), '-beta-', '-AAB-'), '-alpha-', '-AAA-') WHERE display_id IS NOT NULL;

UPDATE pets SET display_id = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(display_id, '-omega-', '-AAX-'), '-psi-', '-AAW-'), '-chi-', '-AAV-'), '-phi-', '-AAU-'), '-upsilon-', '-AAT-'), '-tau-', '-AAS-'), '-sigma-', '-AAR-'), '-rho-', '-AAQ-'), '-pi-', '-AAP-'), '-omicron-', '-AAO-'), '-xi-', '-AAN-'), '-nu-', '-AAM-'), '-mu-', '-AAL-'), '-lambda-', '-AAK-'), '-kappa-', '-AAJ-'), '-iota-', '-AAI-'), '-theta-', '-AAH-'), '-eta-', '-AAG-'), '-zeta-', '-AAF-'), '-epsilon-', '-AAE-'), '-delta-', '-AAD-'), '-gamma-', '-AAC-'), '-beta-', '-AAB-'), '-alpha-', '-AAA-') WHERE display_id IS NOT NULL;

UPDATE emails SET display_id = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(display_id, '-omega-', '-AAX-'), '-psi-', '-AAW-'), '-chi-', '-AAV-'), '-phi-', '-AAU-'), '-upsilon-', '-AAT-'), '-tau-', '-AAS-'), '-sigma-', '-AAR-'), '-rho-', '-AAQ-'), '-pi-', '-AAP-'), '-omicron-', '-AAO-'), '-xi-', '-AAN-'), '-nu-', '-AAM-'), '-mu-', '-AAL-'), '-lambda-', '-AAK-'), '-kappa-', '-AAJ-'), '-iota-', '-AAI-'), '-theta-', '-AAH-'), '-eta-', '-AAG-'), '-zeta-', '-AAF-'), '-epsilon-', '-AAE-'), '-delta-', '-AAD-'), '-gamma-', '-AAC-'), '-beta-', '-AAB-'), '-alpha-', '-AAA-') WHERE display_id IS NOT NULL;

UPDATE phones SET display_id = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(display_id, '-omega-', '-AAX-'), '-psi-', '-AAW-'), '-chi-', '-AAV-'), '-phi-', '-AAU-'), '-upsilon-', '-AAT-'), '-tau-', '-AAS-'), '-sigma-', '-AAR-'), '-rho-', '-AAQ-'), '-pi-', '-AAP-'), '-omicron-', '-AAO-'), '-xi-', '-AAN-'), '-nu-', '-AAM-'), '-mu-', '-AAL-'), '-lambda-', '-AAK-'), '-kappa-', '-AAJ-'), '-iota-', '-AAI-'), '-theta-', '-AAH-'), '-eta-', '-AAG-'), '-zeta-', '-AAF-'), '-epsilon-', '-AAE-'), '-delta-', '-AAD-'), '-gamma-', '-AAC-'), '-beta-', '-AAB-'), '-alpha-', '-AAA-') WHERE display_id IS NOT NULL;

UPDATE route_interests SET display_id = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(display_id, '-omega-', '-AAX-'), '-psi-', '-AAW-'), '-chi-', '-AAV-'), '-phi-', '-AAU-'), '-upsilon-', '-AAT-'), '-tau-', '-AAS-'), '-sigma-', '-AAR-'), '-rho-', '-AAQ-'), '-pi-', '-AAP-'), '-omicron-', '-AAO-'), '-xi-', '-AAN-'), '-nu-', '-AAM-'), '-mu-', '-AAL-'), '-lambda-', '-AAK-'), '-kappa-', '-AAJ-'), '-iota-', '-AAI-'), '-theta-', '-AAH-'), '-eta-', '-AAG-'), '-zeta-', '-AAF-'), '-epsilon-', '-AAE-'), '-delta-', '-AAD-'), '-gamma-', '-AAC-'), '-beta-', '-AAB-'), '-alpha-', '-AAA-') WHERE display_id IS NOT NULL;

UPDATE route_interest_expressions SET display_id = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(display_id, '-omega-', '-AAX-'), '-psi-', '-AAW-'), '-chi-', '-AAV-'), '-phi-', '-AAU-'), '-upsilon-', '-AAT-'), '-tau-', '-AAS-'), '-sigma-', '-AAR-'), '-rho-', '-AAQ-'), '-pi-', '-AAP-'), '-omicron-', '-AAO-'), '-xi-', '-AAN-'), '-nu-', '-AAM-'), '-mu-', '-AAL-'), '-lambda-', '-AAK-'), '-kappa-', '-AAJ-'), '-iota-', '-AAI-'), '-theta-', '-AAH-'), '-eta-', '-AAG-'), '-zeta-', '-AAF-'), '-epsilon-', '-AAE-'), '-delta-', '-AAD-'), '-gamma-', '-AAC-'), '-beta-', '-AAB-'), '-alpha-', '-AAA-') WHERE display_id IS NOT NULL;

UPDATE social_ids SET display_id = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(display_id, '-omega-', '-AAX-'), '-psi-', '-AAW-'), '-chi-', '-AAV-'), '-phi-', '-AAU-'), '-upsilon-', '-AAT-'), '-tau-', '-AAS-'), '-sigma-', '-AAR-'), '-rho-', '-AAQ-'), '-pi-', '-AAP-'), '-omicron-', '-AAO-'), '-xi-', '-AAN-'), '-nu-', '-AAM-'), '-mu-', '-AAL-'), '-lambda-', '-AAK-'), '-kappa-', '-AAJ-'), '-iota-', '-AAI-'), '-theta-', '-AAH-'), '-eta-', '-AAG-'), '-zeta-', '-AAF-'), '-epsilon-', '-AAE-'), '-delta-', '-AAD-'), '-gamma-', '-AAC-'), '-beta-', '-AAB-'), '-alpha-', '-AAA-') WHERE display_id IS NOT NULL;

UPDATE error_log SET display_id = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(display_id, '-omega-', '-AAX-'), '-psi-', '-AAW-'), '-chi-', '-AAV-'), '-phi-', '-AAU-'), '-upsilon-', '-AAT-'), '-tau-', '-AAS-'), '-sigma-', '-AAR-'), '-rho-', '-AAQ-'), '-pi-', '-AAP-'), '-omicron-', '-AAO-'), '-xi-', '-AAN-'), '-nu-', '-AAM-'), '-mu-', '-AAL-'), '-lambda-', '-AAK-'), '-kappa-', '-AAJ-'), '-iota-', '-AAI-'), '-theta-', '-AAH-'), '-eta-', '-AAG-'), '-zeta-', '-AAF-'), '-epsilon-', '-AAE-'), '-delta-', '-AAD-'), '-gamma-', '-AAC-'), '-beta-', '-AAB-'), '-alpha-', '-AAA-') WHERE display_id IS NOT NULL;

UPDATE front_sync_runs SET display_id = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(display_id, '-omega-', '-AAX-'), '-psi-', '-AAW-'), '-chi-', '-AAV-'), '-phi-', '-AAU-'), '-upsilon-', '-AAT-'), '-tau-', '-AAS-'), '-sigma-', '-AAR-'), '-rho-', '-AAQ-'), '-pi-', '-AAP-'), '-omicron-', '-AAO-'), '-xi-', '-AAN-'), '-nu-', '-AAM-'), '-mu-', '-AAL-'), '-lambda-', '-AAK-'), '-kappa-', '-AAJ-'), '-iota-', '-AAI-'), '-theta-', '-AAH-'), '-eta-', '-AAG-'), '-zeta-', '-AAF-'), '-epsilon-', '-AAE-'), '-delta-', '-AAD-'), '-gamma-', '-AAC-'), '-beta-', '-AAB-'), '-alpha-', '-AAA-') WHERE display_id IS NOT NULL;

UPDATE opportunities SET display_id = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(display_id, '-omega-', '-AAX-'), '-psi-', '-AAW-'), '-chi-', '-AAV-'), '-phi-', '-AAU-'), '-upsilon-', '-AAT-'), '-tau-', '-AAS-'), '-sigma-', '-AAR-'), '-rho-', '-AAQ-'), '-pi-', '-AAP-'), '-omicron-', '-AAO-'), '-xi-', '-AAN-'), '-nu-', '-AAM-'), '-mu-', '-AAL-'), '-lambda-', '-AAK-'), '-kappa-', '-AAJ-'), '-iota-', '-AAI-'), '-theta-', '-AAH-'), '-eta-', '-AAG-'), '-zeta-', '-AAF-'), '-epsilon-', '-AAE-'), '-delta-', '-AAD-'), '-gamma-', '-AAC-'), '-beta-', '-AAB-'), '-alpha-', '-AAA-') WHERE display_id IS NOT NULL;

UPDATE general_leads SET display_id = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(display_id, '-omega-', '-AAX-'), '-psi-', '-AAW-'), '-chi-', '-AAV-'), '-phi-', '-AAU-'), '-upsilon-', '-AAT-'), '-tau-', '-AAS-'), '-sigma-', '-AAR-'), '-rho-', '-AAQ-'), '-pi-', '-AAP-'), '-omicron-', '-AAO-'), '-xi-', '-AAN-'), '-nu-', '-AAM-'), '-mu-', '-AAL-'), '-lambda-', '-AAK-'), '-kappa-', '-AAJ-'), '-iota-', '-AAI-'), '-theta-', '-AAH-'), '-eta-', '-AAG-'), '-zeta-', '-AAF-'), '-epsilon-', '-AAE-'), '-delta-', '-AAD-'), '-gamma-', '-AAC-'), '-beta-', '-AAB-'), '-alpha-', '-AAA-') WHERE display_id IS NOT NULL;
