/**
 * Machine-readable error codes for all API errors.
 * Organized by domain.
 */
export const ERROR_CODES = {
  // Auth
  AUTH_REQUIRED: "AUTH_REQUIRED",
  AUTH_INVALID_SESSION: "AUTH_INVALID_SESSION",
  AUTH_INSUFFICIENT_PERMS: "AUTH_INSUFFICIENT_PERMS",
  AUTH_ACCESS_DENIED: "AUTH_ACCESS_DENIED",
  AUTH_ACCOUNT_DEACTIVATED: "AUTH_ACCOUNT_DEACTIVATED",
  AUTH_OAUTH_MISSING_PARAMS: "AUTH_OAUTH_MISSING_PARAMS",
  AUTH_OAUTH_INVALID_STATE: "AUTH_OAUTH_INVALID_STATE",
  AUTH_OAUTH_TOKEN_FAILED: "AUTH_OAUTH_TOKEN_FAILED",
  AUTH_OAUTH_USER_INFO_FAILED: "AUTH_OAUTH_USER_INFO_FAILED",
  AUTH_OAUTH_CANCELLED: "AUTH_OAUTH_CANCELLED",

  // Validation
  VALIDATION_FAILED: "VALIDATION_FAILED",

  // System
  INTERNAL_ERROR: "INTERNAL_ERROR",

  // Not Found
  HUMAN_NOT_FOUND: "HUMAN_NOT_FOUND",
  ACCOUNT_NOT_FOUND: "ACCOUNT_NOT_FOUND",
  ACTIVITY_NOT_FOUND: "ACTIVITY_NOT_FOUND",
  FLIGHT_NOT_FOUND: "FLIGHT_NOT_FOUND",
  BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",
  PET_NOT_FOUND: "PET_NOT_FOUND",
  COLLEAGUE_NOT_FOUND: "COLLEAGUE_NOT_FOUND",
  EMAIL_NOT_FOUND: "EMAIL_NOT_FOUND",
  PHONE_NUMBER_NOT_FOUND: "PHONE_NUMBER_NOT_FOUND",
  DOCUMENT_NOT_FOUND: "DOCUMENT_NOT_FOUND",
  GEO_INTEREST_NOT_FOUND: "GEO_INTEREST_NOT_FOUND",
  GEO_EXPRESSION_NOT_FOUND: "GEO_EXPRESSION_NOT_FOUND",
  ROUTE_INTEREST_NOT_FOUND: "ROUTE_INTEREST_NOT_FOUND",
  ROUTE_EXPRESSION_NOT_FOUND: "ROUTE_EXPRESSION_NOT_FOUND",
  AUDIT_ENTRY_NOT_FOUND: "AUDIT_ENTRY_NOT_FOUND",
  ROUTE_SIGNUP_NOT_FOUND: "ROUTE_SIGNUP_NOT_FOUND",
  WEBSITE_BOOKING_REQUEST_NOT_FOUND: "WEBSITE_BOOKING_REQUEST_NOT_FOUND",

  // Business logic
  HUMAN_DUPLICATE_NAME: "HUMAN_DUPLICATE_NAME",
  RELATIONSHIP_NOT_FOUND: "RELATIONSHIP_NOT_FOUND",
  RELATIONSHIP_DUPLICATE: "RELATIONSHIP_DUPLICATE",
  COLLEAGUE_EMAIL_EXISTS: "COLLEAGUE_EMAIL_EXISTS",
  INVALID_CONFIG_TYPE: "INVALID_CONFIG_TYPE",
  NO_FIELDS_TO_UPDATE: "NO_FIELDS_TO_UPDATE",
  UNDO_NOT_SUPPORTED: "UNDO_NOT_SUPPORTED",
  NO_CHANGES_TO_UNDO: "NO_CHANGES_TO_UNDO",
  FILE_NOT_PROVIDED: "FILE_NOT_PROVIDED",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  SUPABASE_ERROR: "SUPABASE_ERROR",
  ERROR_LOG_NOT_FOUND: "ERROR_LOG_NOT_FOUND",
  EMAIL_DUPLICATE: "EMAIL_DUPLICATE",
  PHONE_DUPLICATE: "PHONE_DUPLICATE",
  SOCIAL_ID_DUPLICATE: "SOCIAL_ID_DUPLICATE",
  WEBSITE_DUPLICATE: "WEBSITE_DUPLICATE",
  ACTIVITY_DUPLICATE_FRONT_ID: "ACTIVITY_DUPLICATE_FRONT_ID",
  FRONT_SYNC_FAILED: "FRONT_SYNC_FAILED",
  FRONT_SYNC_RUN_NOT_FOUND: "FRONT_SYNC_RUN_NOT_FOUND",
  FRONT_SYNC_REVERT_FAILED: "FRONT_SYNC_REVERT_FAILED",
  CONFIG_LAST_TYPE: "CONFIG_LAST_TYPE",
  CONFIG_TYPE_IN_USE: "CONFIG_TYPE_IN_USE",
  SOCIAL_ID_NOT_FOUND: "SOCIAL_ID_NOT_FOUND",
  WEBSITE_NOT_FOUND: "WEBSITE_NOT_FOUND",
  REFERRAL_CODE_NOT_FOUND: "REFERRAL_CODE_NOT_FOUND",
  DISCOUNT_CODE_NOT_FOUND: "DISCOUNT_CODE_NOT_FOUND",

  // Opportunities
  OPPORTUNITY_NOT_FOUND: "OPPORTUNITY_NOT_FOUND",
  OPPORTUNITY_LINK_NOT_FOUND: "OPPORTUNITY_LINK_NOT_FOUND",
  OPPORTUNITY_PRIMARY_REQUIRED: "OPPORTUNITY_PRIMARY_REQUIRED",
  OPPORTUNITY_PET_OWNER_NOT_LINKED: "OPPORTUNITY_PET_OWNER_NOT_LINKED",
  OPPORTUNITY_NEXT_ACTION_REQUIRED: "OPPORTUNITY_NEXT_ACTION_REQUIRED",
  OPPORTUNITY_LOSS_REASON_REQUIRED: "OPPORTUNITY_LOSS_REASON_REQUIRED",
  OPPORTUNITY_CODE_EXHAUSTED: "OPPORTUNITY_CODE_EXHAUSTED",
  CADENCE_CONFIG_NOT_FOUND: "CADENCE_CONFIG_NOT_FOUND",

  // Agreements
  AGREEMENT_NOT_FOUND: "AGREEMENT_NOT_FOUND",
  DOCUMENT_INVALID_TYPE: "DOCUMENT_INVALID_TYPE",

  // General Leads
  GENERAL_LEAD_NOT_FOUND: "GENERAL_LEAD_NOT_FOUND",
  GENERAL_LEAD_REJECT_REASON_REQUIRED: "GENERAL_LEAD_REJECT_REASON_REQUIRED",
  GENERAL_LEAD_LOSS_REASON_REQUIRED: "GENERAL_LEAD_LOSS_REASON_REQUIRED",
  GENERAL_LEAD_INVALID_STATUS_TRANSITION: "GENERAL_LEAD_INVALID_STATUS_TRANSITION",
  GENERAL_LEAD_ALREADY_CONVERTED: "GENERAL_LEAD_ALREADY_CONVERTED",
  GENERAL_LEAD_CLOSED: "GENERAL_LEAD_CLOSED",
  LEAD_ALREADY_LINKED: "LEAD_ALREADY_LINKED",

  // Front Import
  FRONT_IMPORT_ALREADY_EXISTS: "FRONT_IMPORT_ALREADY_EXISTS",
  FRONT_IMPORT_NO_CONTACT: "FRONT_IMPORT_NO_CONTACT",

  // Marketing Attributions
  MARKETING_ATTRIBUTION_NOT_FOUND: "MARKETING_ATTRIBUTION_NOT_FOUND",

  // Lead Scores
  LEAD_SCORE_NOT_FOUND: "LEAD_SCORE_NOT_FOUND",
  LEAD_SCORE_INVALID_PARENT: "LEAD_SCORE_INVALID_PARENT",

  // Evacuation Leads
  EVACUATION_LEAD_NOT_FOUND: "EVACUATION_LEAD_NOT_FOUND",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
