/**
 * Machine-readable error codes for all API errors.
 * Organized by domain.
 */
export const ERROR_CODES = {
  // Auth
  AUTH_REQUIRED: "AUTH_REQUIRED",
  AUTH_INVALID_SESSION: "AUTH_INVALID_SESSION",
  AUTH_INSUFFICIENT_PERMS: "AUTH_INSUFFICIENT_PERMS",
  AUTH_ACCESS_DENIED: "AUTH_ACCESS_DENIED",
  AUTH_ACCOUNT_DEACTIVATED: "AUTH_ACCOUNT_DEACTIVATED",
  AUTH_OAUTH_MISSING_PARAMS: "AUTH_OAUTH_MISSING_PARAMS",
  AUTH_OAUTH_INVALID_STATE: "AUTH_OAUTH_INVALID_STATE",
  AUTH_OAUTH_TOKEN_FAILED: "AUTH_OAUTH_TOKEN_FAILED",
  AUTH_OAUTH_USER_INFO_FAILED: "AUTH_OAUTH_USER_INFO_FAILED",

  // Validation
  VALIDATION_FAILED: "VALIDATION_FAILED",

  // System
  INTERNAL_ERROR: "INTERNAL_ERROR",

  // Not Found
  HUMAN_NOT_FOUND: "HUMAN_NOT_FOUND",
  ACCOUNT_NOT_FOUND: "ACCOUNT_NOT_FOUND",
  ACTIVITY_NOT_FOUND: "ACTIVITY_NOT_FOUND",
  FLIGHT_NOT_FOUND: "FLIGHT_NOT_FOUND",
  BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",
  PET_NOT_FOUND: "PET_NOT_FOUND",
  COLLEAGUE_NOT_FOUND: "COLLEAGUE_NOT_FOUND",
  EMAIL_NOT_FOUND: "EMAIL_NOT_FOUND",
  PHONE_NUMBER_NOT_FOUND: "PHONE_NUMBER_NOT_FOUND",
  DOCUMENT_NOT_FOUND: "DOCUMENT_NOT_FOUND",
  GEO_INTEREST_NOT_FOUND: "GEO_INTEREST_NOT_FOUND",
  GEO_EXPRESSION_NOT_FOUND: "GEO_EXPRESSION_NOT_FOUND",
  ROUTE_INTEREST_NOT_FOUND: "ROUTE_INTEREST_NOT_FOUND",
  ROUTE_EXPRESSION_NOT_FOUND: "ROUTE_EXPRESSION_NOT_FOUND",
  AUDIT_ENTRY_NOT_FOUND: "AUDIT_ENTRY_NOT_FOUND",
  ROUTE_SIGNUP_NOT_FOUND: "ROUTE_SIGNUP_NOT_FOUND",
  WEBSITE_BOOKING_REQUEST_NOT_FOUND: "WEBSITE_BOOKING_REQUEST_NOT_FOUND",

  // Business logic
  COLLEAGUE_EMAIL_EXISTS: "COLLEAGUE_EMAIL_EXISTS",
  INVALID_CONFIG_TYPE: "INVALID_CONFIG_TYPE",
  NO_FIELDS_TO_UPDATE: "NO_FIELDS_TO_UPDATE",
  UNDO_NOT_SUPPORTED: "UNDO_NOT_SUPPORTED",
  NO_CHANGES_TO_UNDO: "NO_CHANGES_TO_UNDO",
  FILE_NOT_PROVIDED: "FILE_NOT_PROVIDED",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  SUPABASE_ERROR: "SUPABASE_ERROR",
  ERROR_LOG_NOT_FOUND: "ERROR_LOG_NOT_FOUND",
  FRONT_SYNC_FAILED: "FRONT_SYNC_FAILED",
  SOCIAL_ID_NOT_FOUND: "SOCIAL_ID_NOT_FOUND",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
