import { z } from "zod";

const primaryHumanSchema = z.object({
  id: z.string(),
  displayId: z.string(),
  firstName: z.string(),
  lastName: z.string(),
}).passthrough();

export const opportunityListItemSchema = z.object({
  id: z.string(),
  displayId: z.string(),
  stage: z.string(),
  seatsRequested: z.number(),
  passengerSeats: z.number(),
  petSeats: z.number(),
  notes: z.string().nullable(),
  lossReason: z.string().nullable(),
  lossNotes: z.string().nullable(),
  ownerId: z.string().nullable(),
  nextActionOwnerId: z.string().nullable(),
  nextActionDescription: z.string().nullable(),
  nextActionType: z.string().nullable(),
  nextActionStartDate: z.string().nullable(),
  nextActionDueDate: z.string().nullable(),
  nextActionCompletedAt: z.string().nullable(),
  nextActionCadenceNote: z.string().nullable(),
  flightId: z.string().nullable(),
  createdAt: z.string(),
  updatedAt: z.string(),
  primaryHuman: primaryHumanSchema.nullable(),
  primaryHumanName: z.string().nullable(),
  nextActionOwnerName: z.string().nullable(),
  ownerName: z.string().nullable(),
  ownerDisplayId: z.string().nullable(),
  isOverdue: z.boolean(),
  linkedHumanCount: z.number(),
  linkedPetCount: z.number(),
  lastActivityDate: z.string().nullable(),
}).passthrough();

export type OpportunityListItem = z.infer<typeof opportunityListItemSchema>;

export const opportunityDetailSchema = z.object({
  id: z.string(),
  displayId: z.string(),
  stage: z.string(),
  seatsRequested: z.number(),
  passengerSeats: z.number(),
  petSeats: z.number(),
  notes: z.string().nullable(),
  lossReason: z.string().nullable(),
  lossNotes: z.string().nullable(),
  ownerId: z.string().nullable(),
  nextActionOwnerId: z.string().nullable(),
  nextActionDescription: z.string().nullable(),
  nextActionType: z.string().nullable(),
  nextActionStartDate: z.string().nullable(),
  nextActionDueDate: z.string().nullable(),
  nextActionCompletedAt: z.string().nullable(),
  nextActionCadenceNote: z.string().nullable(),
  flightId: z.string().nullable(),
  createdAt: z.string(),
  updatedAt: z.string(),
  linkedHumans: z.array(z.object({
    id: z.string(),
    humanId: z.string(),
    roleId: z.string().nullable(),
    createdAt: z.string(),
    firstName: z.string(),
    lastName: z.string(),
    displayId: z.string(),
    humanName: z.string(),
    humanDisplayId: z.string(),
    roleName: z.string().nullable(),
  }).passthrough()),
  linkedPets: z.array(z.object({
    id: z.string(),
    petId: z.string(),
    createdAt: z.string(),
    name: z.string().nullable(),
    displayId: z.string(),
    type: z.string(),
    humanId: z.string().nullable(),
    petName: z.string(),
    petDisplayId: z.string(),
    petType: z.string(),
    ownerName: z.string().nullable(),
  }).passthrough()),
  linkedBookingRequests: z.array(z.object({
    id: z.string(),
    humanId: z.string(),
    websiteBookingRequestId: z.string(),
    opportunityId: z.string().nullable(),
    linkedAt: z.string(),
  }).passthrough()),
  activities: z.array(z.unknown()),
  nextActionOwnerName: z.string().nullable(),
  ownerName: z.string().nullable(),
  ownerDisplayId: z.string().nullable(),
  isOverdue: z.boolean(),
}).passthrough();

export type OpportunityDetail = z.infer<typeof opportunityDetailSchema>;
